**【問題1】行列積を手計算する**

$A = \left[
\begin{array}{ccc}
  -1 & 2 & 3 \\
  4 & -5 & 6 \\
  7 & 8 & -9
\end{array}
\right],
B = \left[
\begin{array}{ccc}
  0 & 2 & 1 \\
  0 & 2 & -8 \\
  2 & 9 & -1
\end{array}
\right]$


---



$AB = \left[
\begin{array}{ccc}
  0+0+6 & -2+4+27 & -1-16-3 \\
  0+0+12 & 8-10+54 & 4+40-6 \\
  0+0-18 & 14+16-81 & 7-64+9
\end{array}
\right]$

$=\left[
\begin{array}{ccc}
  6 & 29 & -20 \\
  12 & 52 & 38 \\
  -18 & -51 & -48
\end{array}
\right]$



**【問題2】NumPyの関数による計算**

In [154]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

# matmul
print("matmul：{}".format(np.matmul(a_ndarray, b_ndarray)))

# dot
print("dot{}".format(np.dot(a_ndarray, b_ndarray)))

# @
print("dot{}".format(a_ndarray @ b_ndarray))

matmul：[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
dot[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
dot[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


**【問題3】ある要素の計算を実装**

In [155]:
a_ndarray[0,0]*b_ndarray[0,0] + a_ndarray[0,1]*b_ndarray[1,0] + a_ndarray[0,2]*b_ndarray[2,0]
# a_ndarray[0,0]*b_ndarray[0,1] + a_ndarray[0,1]*b_ndarray[1,1] + a_ndarray[0,2]*b_ndarray[2,1]

6

**【問題4】行列積を行う関数の作成**

In [156]:
def calcMatrixProduct( a_ndarray, b_ndarray):

  result_arr = []

  a_clm = a_ndarray.shape[0]
  b_clm = b_ndarray.shape[0]
  a_row = a_ndarray.shape[1]
  b_row = b_ndarray.shape[1]

  # print(a_clm,b_clm,a_row,b_row)

  if not a_clm == b_row:

    print("行列Aの列数と行列Bの行数が不一致です")
    return np.empty

  for i in range(a_clm):

    for j in range(a_row):

      tmp_sum = 0

      for k in range(b_row):

        tmp_sum += a_ndarray[i,k]*b_ndarray[k,j]

      result_arr.append(tmp_sum)

  return np.array(result_arr).reshape(a_clm,b_row)
  




In [157]:
calcMatrixProduct( a_ndarray, b_ndarray)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

**【問題5】計算が定義されない入力を判定する**

In [158]:
d_ndarray_ = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

calcMatrixProduct( d_ndarray_, e_ndarray)

行列Aの列数と行列Bの行数が不一致です


<function numpy.empty>

**【問題6】転置**

In [164]:
print(a_ndarray)
print(b_ndarray.T)

np.dot(a_ndarray, b_ndarray.T)

[[-1  2  3]
 [ 4 -5  6]
 [ 7  8 -9]]
[[ 0  0  2]
 [ 2  2  9]
 [ 1 -8 -1]]


array([[  7, -20,  13],
       [ -4, -58, -43],
       [  7,  88,  95]])